title: Indie 之路
domain: ravenw.com
markdown: rdiscount
pygments: true
regeneration: true
lsi: true
permalink: /blog/:year/:month/:day/:title/
category_dir: ../blog/categories/
tag_dir: ../blog/tags/
tag_title_prefix: 'Tag: '
