title: 小洪
domain: reedhong.github.com
rss: http://feeds.feedburner.com/noding
ga: UA-2922788-2
disqus_shortname: reedhong
comment: 
markdown: rdiscount
pygments: true
regeneration: true
lsi: true
permalink: /blog/:year/:month/:day/:title/
category_dir: ../blog/categories/
tag_dir: ../blog/tags/
tag_title_prefix: 'Tag: '
